### ISSUE TITLE
Assignment Seven

### ISSUE THREAD

**Issue by quindariuss** [quindariuss/Computer-Graphics-and-Multimedia#30]
### Start with your previous assignment (your scene with a skybox) and add lighting effects as we have studied in Module 7: ambient, diffuse, and specular. Use a single light source, either point source or directional as you choose.

- Add a buffer for normal vectors to the vertex shader
- Reorganize the transformations used in the vertex shader
	- Need three transformations (see shading example for how to compute these)
		- Model-view transformation
		- Projection transformation
		- Normal transformation
	- The model-view transform applied to the vertex position is sent to the fragment shader
	- Apply both the projection and model-view to the vertex postion for gl_Position
	- Apply the normal transformation to the normal vector for the vertex to send to the fragment shader
- Many new uniform variables related to lighting and material color to send to the fragment shader
- Instead of assigning to fColor (the output from the fragment shader) from the sampler (or however you did it), assign to a different variable
	- Use this value for the material color in the shading calculations
- You may want to adjust the specular strength in each object, if the value is large the effect can be too much

**Comment by quinwoods** [comment]
![CleanShot 2021-07-27 at 17 34 37@2x](https://user-images.githubusercontent.com/44750253/127230586-e93698d2-4538-4b73-a046-43df03aeff68.jpg)
![CleanShot 2021-07-27 at 17 17 51@2x](https://user-images.githubusercontent.com/44750253/127230594-ffb6be53-4ff0-4272-aa64-bb915c18df11.jpg)
![CleanShot 2021-07-27 at 17 15 23@2x](https://user-images.githubusercontent.com/44750253/127230597-57c7d1d3-94c6-4b57-9261-da04e47fb4ba.jpg)

**Comment by quinwoods** [comment]
![CleanShot 2021-07-27 at 17 44 18@2x](https://user-images.githubusercontent.com/44750253/127231618-b61b5bb2-60b2-4b81-bf5e-8171bc1444c3.jpg)

**Comment by quinwoods** [comment]
vec4 dc;
if (surface_effect == 0) {
dc = diffuse_color * texture (sampler, TextureCoord);
- else if(surface_effect == 1) {
dc = texture(sampler, vTextureCoord);
} else if (surface_effect == 2) {
dc = diffuse_color;

else if (surface_effect == 3)
{
dc = diffuse_color * vcolor;

else {
dc = vec4(0,1,0,1);

//Color = vec4(1,1,0,1);
//Color = texture (sampler, TextureCoord);
vec4 diffuse_component = diffuse_factor * dc * diffuse_light;
vec4 total = ambient_component : diffuse_component + specular_component;
fColor = vec4(total.rgb, 1.0);
//fColor = dc;
//fColor = vec4 (vnn.rbg, 1); //We can check our normals

**Comment by quinwoods** [comment]
```c
vao = cs4722::init_buffers(program, part_list, "bPosition", "", "bTextureCoord", "bNormal");
```

**Comment by quinwoods** [comment]
```c
cs4722::shape* sphere2 = new cs4722::sphere(10, 40);
auto* part4 = new cs4722::part_rotating();
part4->the_shape = (sphere2);
part4->world_transform.translate = (glm::vec3(-1, -.5, -.5));
part4->animation_transform.rotation_axis = (glm::vec3(1, 1, 0));
part4->rotation_rate = (M_PI / 3);
part4->world_transform.scale = (glm::vec3(.4f, .4f, .4f));
part4->animation_transform.rotation_center =
part4->world_transform.matrix() * glm::vec4(0, 0, 0, 1);
/*
* Each part can be assigned a texture unit, this is used in the display function
*/
part4->texture_unit = 3;
part4->surface_material.diffuse_color = cs4722::x11::violet_red;
part4->surface_effect = 0;
part4->surface_material.specular_color = cs4722::x11::white;
part4->surface_material.specular_strength = 30.0;
part4->surface_material.shininess = 10.0;
part_list.push_back(part4);
```

**Comment by quinwoods** [comment]
Done but not proud

**Comment by quinwoods** [comment]
#include "sharing.h"
#include "cs4722/light.h"
#include "cs4722/load_shaders.h"
#include <GLM/gtc/type_ptr.hpp>
#include <GLM/gtc/matrix_inverse.hpp>

#include <iostream>


#include <glad/gl.h>

#include <GLFW/glfw3.h>



#include "cs4722/part.h"
#include "cs4722/buffer_utilities.h"
static cs4722::view *the_view;
static GLuint program;
static std::vector<cs4722::part*> part_list;

static GLuint transform_loc;
static GLuint sampler_loc;

static GLuint vao;
static GLint ambient_light_loc;
static GLint specular_light_loc;
static GLint diffuse_light_loc;
static GLint ambient_color_loc;
static GLint specular_color_loc;
static GLint diffuse_color_loc;
static GLint light_direction_loc; // direction toward the light
static GLint specular_shininess_loc;     // exponent for sharpening highlights
static GLint specular_strength_loc;      // extra factor to adjust shininess
static GLint mv_transform_loc;
static GLint p_transform_loc;
static GLint normal_transform_loc;

static cs4722::light a_light;

void parts_setup(cs4722::view* view)
{

    the_view = view;
    a_light.ambient_light = cs4722::x11::gray25;
//    the_view->enable_logging = true;
    the_view->set_flup(glm::vec3(0.202971,-0.227978,-0.952277),
                       glm::vec3(-0.978031,0,-0.20846),
                       glm::vec3(0.0475242,0.973667,-0.222969),
                       glm::vec3(-0.146291,0.195185,1.3214));



    program = cs4722::load_shaders("parts_vertex_shader02.glsl",
                                   "parts_fragment_shader02.glsl");
    glUseProgram(program);

    ambient_light_loc = glGetUniformLocation(program, "ambient_light");
    specular_light_loc = glGetUniformLocation(program, "specular_light");
    diffuse_light_loc = glGetUniformLocation(program, "diffuse_light");
    ambient_color_loc = glGetUniformLocation(program, "ambient_color");
    specular_color_loc = glGetUniformLocation(program, "specular_color");
    diffuse_color_loc = glGetUniformLocation(program, "diffuse_color");
    light_direction_loc = glGetUniformLocation(program, "light_direction");
    specular_shininess_loc = glGetUniformLocation(program, "specular_shininess");
    specular_strength_loc = glGetUniformLocation(program, "specular_strength");
    // vertex shader uniforms
    mv_transform_loc = glGetUniformLocation(program, "transform");
    p_transform_loc = glGetUniformLocation(program, "p_transform");
    normal_transform_loc = glGetUniformLocation(program, "normal_transform");

    transform_loc = glGetUniformLocation(program, "transform");
    sampler_loc = glGetUniformLocation(program, "sampler");

    glEnable(GL_PROGRAM_POINT_SIZE);
    glEnable(GL_DEPTH_TEST);


    cs4722::init_texture_from_file("../media/tulips-bed-2048x2048.png", 2);
    cs4722::init_texture_computed(1, 8);

    cs4722::init_texture_from_file("../media/galaxy.jpg", 1);
    cs4722::init_texture_from_file("../media/coco.jpg", 2);
    cs4722::init_texture_from_file("../media/dough.jpg", 3);
    cs4722::init_texture_from_file("../media/dough2.jpg", 4);
    cs4722::init_texture_computed(1, 128);

    cs4722::shape* b = new cs4722::sphere(15, 50);
    auto* part = new cs4722::part_rotating();
    part->the_shape = (b);
    part->world_transform.translate = (glm::vec3(.5, -.5, 0));
    part->animation_transform.rotation_axis = (glm::vec3(1, 1, 0));
    part->rotation_rate = (M_PI / 3);
    part->world_transform.scale = (glm::vec3(.4f, .6f, .4f));
    part->animation_transform.rotation_center =
            part->world_transform.matrix() * glm::vec4(0, 0, 0, 1);
    part->texture_unit = 1;
    part->surface_material.specular_color = cs4722::x11::white;
    part->surface_material.specular_strength = 30.0;
    part->surface_material.shininess = 10.0;
    part_list.push_back(part);

    cs4722::shape* sphere2 = new cs4722::sphere(10, 40);
    auto* part7 = new cs4722::part_rotating();
    part7->the_shape = (sphere2);
    part7->world_transform.translate = (glm::vec3(-1, -.5, -.5));
    part7->animation_transform.rotation_axis = (glm::vec3(1, 1, 0));
    part7->rotation_rate = (M_PI / 3);
    part7->world_transform.scale = (glm::vec3(.4f, .4f, .4f));
    part7->animation_transform.rotation_center =
            part7->world_transform.matrix() * glm::vec4(0, 0, 0, 1);
/*
* Each part can be assigned a texture unit, this is used in the display function
*/
    part7->texture_unit = 3;
    part7->surface_material.diffuse_color = cs4722::x11::violet_red;
    part7->surface_effect = 0;
    part7->surface_material.specular_color = cs4722::x11::white;
    part7->surface_material.specular_strength = 30.0;
    part7->surface_material.shininess = 10.0;
    part_list.push_back(part7);


    auto number = 2;
    auto d = 4.0f / (2 * number + 1);
    auto radius = d / 4;
    auto base = -1 + 3 * radius;
    auto center = glm::vec3(base + 1 * d, base + 1 * d, base + 1 * d);

    auto* torus = new cs4722::torus();
    torus->color_set_ = std::vector({cs4722::x11::goldenrod1, cs4722::x11::black});

    auto* object1 = new cs4722::part_rotating();
    object1->the_shape = torus;
    object1->world_transform.translate = center + glm::vec3(0, 0, .25);
    object1->world_transform.scale = glm::vec3(radius, radius, radius);
    object1->animation_transform.rotation_axis = glm::vec3(0, 0, 1);
    object1->animation_transform.rotation_angle = 0;
    object1->animation_transform.rotation_center =
            object1->world_transform.matrix() * glm::vec4(0, 0, 0, 1);
    //obj->set_rotation_rate(glm::linearRand(-M_PI/2, M_PI / 2));
    object1->rotation_rate = M_PI / 3;
    object1->texture_unit= 3;
    part_list.push_back(object1);

    auto* object2 = new cs4722::part_rotating();
    object2->the_shape = torus;
    object2->world_transform.translate = center + glm::vec3(0, 0, 0);
    object2->world_transform.scale = glm::vec3(radius, radius, radius);
    object2->animation_transform.rotation_axis = glm::vec3(0, 0, 1);
    object2->animation_transform.rotation_angle = 0;
    object2->animation_transform.rotation_center =
            object2->world_transform.matrix() * glm::vec4(0, 0, 0, 1);
    //obj->set_rotation_rate(glm::linearRand(-M_PI/2, M_PI / 2));
    object2->rotation_rate = M_PI / 3;
    object2->texture_unit= 4;
    object2->surface_material.specular_color = cs4722::x11::white;
    object2->surface_effect = 0;
    object2->surface_material.diffuse_color = cs4722::x11::red;
    object2->surface_material.specular_strength = 30.0;
    object2->surface_material.shininess = 10.0;
    part_list.push_back(object2);

    cs4722::shape* be = new cs4722::sphere(15, 50);
    auto* parte = new cs4722::part_rotating();
    parte->the_shape = (be);
    parte->world_transform.translate = (glm::vec3(-.5, -.5, 0));
    parte->animation_transform.rotation_axis = (glm::vec3(1, 1, 0));
    parte->rotation_rate = (M_PI / 3);
    parte->world_transform.scale = (glm::vec3(.4f, .4f, .4f));
    parte->animation_transform.rotation_center =
            parte->world_transform.matrix() * glm::vec4(0, 0, 0, 1);
    /*
     * Each part can be assigned a texture unit, this is used in the display function
     */
    parte->texture_unit = 1;
    parte->surface_material.diffuse_color = cs4722::x11::violet_red;
    parte->surface_effect = 1;
    part_list.push_back(parte);

    cs4722::shape* bb = new cs4722::sphere(15, 50);
    auto* part3 = new cs4722::part_rotating();
    part3->the_shape = (bb);
    part3->world_transform.translate = (glm::vec3(.5, -.5, 0));
    part3->animation_transform.rotation_axis = (glm::vec3(1, 1, 0));
    part3->rotation_rate = (M_PI / 3);
    part3->world_transform.scale = (glm::vec3(.4f, .4f, .4f));
    part3->animation_transform.rotation_center =
            part3->world_transform.matrix() * glm::vec4(0, 0, 0, 1);
    /*
     * Each part can be assigned a texture unit, this is used in the display function
     */
    part3->texture_unit = 2;
    part3->surface_material.diffuse_color = cs4722::x11::rosy_brown;
    part3->surface_effect = 1;
    part_list.push_back(part3);




    cs4722::shape* b1 = new cs4722::block();
    auto* part1 = new cs4722::part_rotating();
    part1->the_shape = (b1);
    part1->world_transform.translate = (glm::vec3(-.5, .5, 0));
    part1->animation_transform.rotation_axis = (glm::vec3(1, 0, 1));
    part1->rotation_rate = (M_PI / 3);
    part1->world_transform.scale = (glm::vec3(.4f, .4f, .4f));
    part1->animation_transform.rotation_center =
            part1->world_transform.matrix() * glm::vec4(0, .3f, 0, 1);
    part1->texture_unit = 2;
    part1->surface_material.diffuse_color = cs4722::x11::slate_blue;
    part1->surface_effect = 0;
    part1->surface_material.specular_color = cs4722::x11::white;
    part1->surface_material.specular_strength = 30.0;
    part1->surface_material.shininess = 10.0;
    part_list.push_back(part1);

    b1 = new cs4722::cylinder();
    part1 = new cs4722::part_rotating();
    part1->the_shape = (b1);
    part1->world_transform.translate = (glm::vec3(.5, .5, 0));
    part1->animation_transform.rotation_axis = (glm::vec3(1, 0, 1));
    part1->rotation_rate = (M_PI / 3);
    part1->world_transform.scale = (glm::vec3(.4f, .4f, .4f));
    part1->animation_transform.rotation_center =
            part1->world_transform.matrix() * glm::vec4(0, .3f, 0, 1);
    part1->texture_unit = 1;
    part1->surface_material.diffuse_color = cs4722::x11::olive_drab;
    part1->surface_effect = 2;
    part1->surface_material.specular_color = cs4722::x11::white;
    part1->surface_material.specular_strength = 30.0;
    part1->surface_material.shininess = 10.0;
    part_list.push_back(part1);

    cs4722::shape* bbb = new cs4722::block();
    auto* part4 = new cs4722::part_rotating();
    part4->the_shape = (bbb);
    part4->world_transform.translate = (glm::vec3(-.75, .5, 0));
    part4->animation_transform.rotation_axis = (glm::vec3(1, 0, 1));
    part4->rotation_rate = (M_PI / 3);
    part4->world_transform.scale = (glm::vec3(.4f, .4f, .4f));
    part4->animation_transform.rotation_center =
            part1->world_transform.matrix() * glm::vec4(0, .3f, 0, 1);
    part4->texture_unit = 1;
    part4->surface_material.diffuse_color = cs4722::x11::slate_blue;
    part4->surface_effect = 0;
    part_list.push_back(part4);

    b1 = new cs4722::cylinder();
    part1 = new cs4722::part_rotating();
    part1->the_shape = (b1);
    part1->world_transform.translate = (glm::vec3(.5, .5, 0));
    part1->animation_transform.rotation_axis = (glm::vec3(1, 0, 1));
    part1->rotation_rate = (M_PI / 3);
    part1->world_transform.scale = (glm::vec3(.4f, .4f, .4f));
    part1->animation_transform.rotation_center =
            part1->world_transform.matrix() * glm::vec4(0, .3f, 0, 1);
    part1->texture_unit = 1;
    part1->surface_material.diffuse_color = cs4722::x11::olive_drab;
    part1->surface_effect = 2;
    part1->surface_material.specular_color = cs4722::x11::white;
    part1->surface_material.specular_strength = 30.0;
    part1->surface_material.shininess = 10.0;
    part_list.push_back(part1);

    b1 = new cs4722::cylinder();
    part1 = new cs4722::part_rotating();
    part1->the_shape = (b1);
    part1->world_transform.translate = (glm::vec3(.75, .75, 0));
    part1->animation_transform.rotation_axis = (glm::vec3(1, 0, 1));
    part1->rotation_rate = (M_PI / 3);
    part1->world_transform.scale = (glm::vec3(.4f, .4f, .4f));
    part1->animation_transform.rotation_center =
            part1->world_transform.matrix() * glm::vec4(0, .3f, 0, 1);
    part1->texture_unit = 1;
    part1->surface_material.diffuse_color = cs4722::x11::indian_red;
    part1->surface_effect = 2;
    part1->surface_material.specular_color = cs4722::x11::white;
    part1->surface_material.specular_strength = 30.0;
    part1->surface_material.shininess = 10.0;
    part_list.push_back(part1);


    cs4722::shape* b1e = new cs4722::block();
    auto* part1e = new cs4722::part_rotating();
    part1e->the_shape = (b1e);
    part1e->world_transform.translate = (glm::vec3(-.5, 0, 0));
    part1e->animation_transform.rotation_axis = (glm::vec3(1, 0, 1));
    part1e->rotation_rate = (M_PI / 3);
    part1e->world_transform.scale = (glm::vec3(.2f, .6f, .2f));
    part1e->animation_transform.rotation_center =
            part1e->world_transform.matrix() * glm::vec4(0, .3f, 0, 1);
    part1e->texture_unit = 2;
    part1e->surface_effect= 1;
    part1e->surface_material.specular_color = cs4722::x11::white;
    part1e->surface_material.specular_strength = 30.0;
            part1e->surface_material.shininess = 10.0;

    part_list.push_back(part1e);



    vao = cs4722::init_buffers(program, part_list, "bPosition", "", "vTextureCoord", "bNormal");

}


//----------------------------------------------------------------------------
//
// display
//


void parts_display()
{

    // bind the VAO for this set of vertex buffers
    glBindVertexArray(vao);
    // since we have multiple sets of shader programs, we must activate the one we want to use
    glUseProgram(program);


    auto view_transform = glm::lookAt(the_view->camera_position,
                                      the_view->camera_position + the_view->camera_forward,
                                      the_view->camera_up);
    auto projection_transform = glm::infinitePerspective(the_view->perspective_fovy,
                                                         the_view->perspective_aspect, the_view->perspective_near);
    glUniform4fv(light_direction_loc, 1,
                 glm::value_ptr( view_transform *  a_light.light_direction_position));
    auto vp_transform = projection_transform * view_transform;

    static auto last_time = 0.0;
    auto time = glfwGetTime();
    auto delta_time = time - last_time;
    last_time = time;


//    for (auto part : part_list) {
//        part->animate(time, delta_time);
//        auto model_transform = part->animation_transform.matrix() * part->world_transform.matrix();
//        auto transform = vp_transform * model_transform;
//        glUniformMatrix4fv(transform_loc, 1, GL_FALSE, glm::value_ptr(transform));
//        glUniform1i(sampler_loc, part->texture_unit);
//        glDrawArrays(GL_TRIANGLES, part->the_shape->buffer_start, part->the_shape->buffer_size);
//    }
    for (auto obj: part_list) {

        obj->animate(time, delta_time);
        glUniform1i(sampler_loc, obj->texture_unit);
        auto model_transform = obj->animation_transform.matrix() * obj->world_transform.matrix();
        auto mv_transform = view_transform *
                            obj->animation_transform.matrix() * obj->world_transform.matrix();


        glUniformMatrix4fv(mv_transform_loc, 1, GL_FALSE, glm::value_ptr(mv_transform));
        glUniformMatrix4fv(p_transform_loc, 1, GL_FALSE, glm::value_ptr(projection_transform));
        glUniformMatrix4fv(normal_transform_loc, 1, GL_FALSE,
                           glm::value_ptr(glm::inverseTranspose(mv_transform)));
        glUniform4fv(diffuse_color_loc,1, obj->surface_material.diffuse_color.as_float());

//        glm::vec4 ambient_product = *a_light.ambient_light.as_vec4()
//                * *obj->surface_material.ambient_color.as_vec4();
//        glm::vec4 diffuse_product = *a_light.diffuse_light.as_vec4()
//                                    * *obj->surface_material.diffuse_color.as_vec4();
//        glm::vec4 specular_product = *a_light.specular_light.as_vec4()
//                                    * *obj->surface_material.specular_color.as_vec4();

        glUniform4fv(ambient_light_loc, 1, a_light.ambient_light.as_float());
        glUniform4fv(diffuse_light_loc, 1, a_light.diffuse_light.as_float());
        glUniform4fv(specular_light_loc, 1, a_light.specular_light.as_float());
        glUniform4fv(ambient_color_loc, 1, obj->surface_material.ambient_color.as_float());
        glUniform4fv(diffuse_color_loc, 1,  obj->surface_material.diffuse_color.as_float());
        glUniform4fv(specular_color_loc, 1, obj->surface_material.specular_color.as_float());
        glUniform1f(specular_shininess_loc, obj->surface_material.shininess);
        glUniform1f(specular_strength_loc, obj->surface_material.specular_strength);


        glDrawArrays(GL_TRIANGLES, obj->the_shape->buffer_start,
                     obj->the_shape->buffer_size);

    }
}

**Comment by quinwoods** [comment]
#version 430 core

out vec4 fColor;

in vec4 vcolor;
in vec2 vTextureCoord;
in vec4 vNormal;
in vec4 vPosition;


uniform vec4 ambient_light;
uniform vec4 specular_light;
uniform vec4 diffuse_light;
uniform vec4 ambient_color;
uniform vec4 specular_color;
uniform vec4 diffuse_color;
uniform int surface_effect;

uniform vec4 light_direction; // direction toward the light
uniform float specular_shininess;     // exponent for sharpening highlights
uniform float specular_strength;      // extra factor to adjust shininess

uniform sampler2D  sampler;

void main()
{
    vec3 half_vector = normalize(normalize(-light_direction.xyz) - normalize(vPosition.xyz));

    vec4 vnn = normalize(vNormal);

    float diffuse_factor = max(0.0, dot(vnn, -normalize(light_direction)));
    float specular_factor = max(0.0, dot(vnn.xyz, half_vector));
    if (diffuse_factor == 0.0)
    {specular_factor = 0.0;}
    else
    { specular_factor = pow(specular_factor, specular_shininess) * specular_strength; } // sharpen the highlight

    vec4 bob;
if (surface_effect == 0) {
    bob = diffuse_color * texture (sampler, vTextureCoord);}
    else if(surface_effect == 1) {
    bob = texture(sampler, vTextureCoord);
} else if (surface_effect == 2) {
    bob = diffuse_color;}

else if (surface_effect == 3)
{
    bob = diffuse_color * vcolor;}

else {
    bob = vec4(0,1,0,1);}



vec4 ambient_component = ambient_color * ambient_light;
vec4 diffuse_component = diffuse_factor * diffuse_color * diffuse_light;
vec4 specular_component = specular_factor * specular_color * specular_light;

vec4 total = ambient_component + diffuse_component + specular_component;
fColor = vec4(total.rgb, 1.0);
}

**Comment by quinwoods** [comment]
#version 430 core

in vec4 bPosition;
in vec2 bTextureCoord;
in vec4 bNormal;

uniform mat4 transform;
uniform mat4 p_transform;
uniform mat4 normal_transform;

out vec4 vPosition;
out vec2 vTextureCoord;
out vec4 vNormal;

void
main()
{
    vNormal = normal_transform * bNormal;
    vTextureCoord = bTextureCoord;
    vPosition = transform * bPosition;
    gl_Position = p_transform * vPosition;

}
